# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

require 'spec_helper'

RSpec.describe Usps::Api::Endpoints::CarrierPickupInquiry do
  let(:client) { Usps::Client.new }
  context 'carrier_pickup_inquiry' do
    it 'requires carrier_pickup_inquiry_request' do
      expect { client.carrier_pickup_inquiry }.to raise_error ArgumentError, /Required arguments :carrier_pickup_inquiry_request missing/
    end
  end
end
