# frozen_string_literal: true

# This file was auto-generated by lib/tasks/api.rake

module Usps
	module Api
		module Endpoints
			module CarrierPickupAvailability
				# The Package Pickup
				# Availability API checks the availability for Package Pickup at a specific
				# address and informs the user of the first available date for
				# pickup. Package Pickup is not available for all
				# addresses.
				# @param [Hash] options
				# @option options [required, Hash] carrier_pickup_availability_request 
				#  * *:firm_name* (String) — Use this tag for a firm or company name. FirmName is Optional except if needed to uniquely identify an address. Some firms/companies that have their own ZIP codes require the use of firm name to properly identify their address. Example: <FirmName>ABC Company</FirmName>
				#  * *:suite_or_apt* (required, String) — Use this tag for an apartment or suite number. SuiteOrApt is Optional except if needed to uniquely identify an address at a multiple dwelling address, for example, an apartment building. For example: <SuiteOrApt>Suite 777</SuiteOrApt>
				#  * *:address2* (required, String) — Use this tag for a street address. For example: <Address2>1390 Market Street</Address2>
				#  * *:urbanization* (required, String) — Use this tag for Urbanization (for Puerto Rico only). ZIP Code prefixes 006 to 009, if area is so designated.
				#  * *:city* (required, String) — Use this tag for a city. Either ZIP5 or City and State are Required. For example: <City>Houston</City>
				#  * *:state* (required, String) — Use this tag for a state abbreviation. Either ZIP5 or City and State are Required. For example: <State>TX</State>
				#  * *:zip5* (required, String) — Use this tag for a 5 digit ZIP Code. Either ZIP5 or City and State are Required. For example: <ZIP5>77058</ZIP5>
				#  * *:zip4* (required, String) — Maximum characters allowed: 4. For example: <ZIP4>1234</ZIP4>
				#  * *:date* (String) — Use this tag to request a pickup date/time. For example: 2006-05-04T18:13:51.0Z
def carrier_pickup_availability(options = {})
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request missing') if options[:carrier_pickup_availability_request].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :suite_or_apt missing') if options[:carrier_pickup_availability_request][:suite_or_apt].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :address2 missing') if options[:carrier_pickup_availability_request][:address2].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :urbanization missing') if options[:carrier_pickup_availability_request][:urbanization].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :city missing') if options[:carrier_pickup_availability_request][:city].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :state missing') if options[:carrier_pickup_availability_request][:state].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :zip5 missing') if options[:carrier_pickup_availability_request][:zip5].nil?
					throw ArgumentError.new('Required arguments :carrier_pickup_availability_request, :zip4 missing') if options[:carrier_pickup_availability_request][:zip4].nil?

					request = build_request(:carrier_pickup_availability, options)
					get('https://secure.shippingapis.com/ShippingAPI.dll', {
						API: 'CarrierPickupAvailability',
						XML: request,
					})
				end

				private

				def tag_unless_blank(xml, tag_name, data)
					xml.tag!(tag_name, data) unless data.blank? || data.nil?
				end

				def build_carrier_pickup_availability_request(xml, options = {})
					tag_unless_blank(xml, 'FirmName', options[:carrier_pickup_availability_request][:firm_name])
					xml.tag!('SuiteOrApt', options[:carrier_pickup_availability_request][:suite_or_apt])
					xml.tag!('Address2', options[:carrier_pickup_availability_request][:address2])
					xml.tag!('Urbanization', options[:carrier_pickup_availability_request][:urbanization])
					xml.tag!('City', options[:carrier_pickup_availability_request][:city])
					xml.tag!('State', options[:carrier_pickup_availability_request][:state])
					xml.tag!('ZIP5', options[:carrier_pickup_availability_request][:zip5])
					xml.tag!('ZIP4', options[:carrier_pickup_availability_request][:zip4])
					tag_unless_blank(xml, 'Date', options[:carrier_pickup_availability_request][:date])
					xml.target!
				end

			end
		end
	end
end
